language: go
go:
  - "1.12"
env:
  - GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
before_script:
  #- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
script:
  #- golangci-lint run
  - go build